/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * GSVacGUI.java
 *
 */
package GSVacProgram;

import java.util.ArrayList;

/**
 *
 * @author gshaw
 */
public class GSVacGUI extends javax.swing.JFrame {

    /**
     * Creates new form GSVacGUI
     */
    private PQInterface myPQueue;
    private ArrayList<String> n = new ArrayList<String>();
    private ArrayList<String> a = new ArrayList<String>();
    private ArrayList<String> u = new ArrayList<String>();

    public GSVacGUI() {
        myPQueue = new MyPriorityQueue();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeJLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ulLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        numVacBTN = new javax.swing.JButton();
        addPatientBTN = new javax.swing.JButton();
        VacBTN = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        exitBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        ageLabel = new javax.swing.JLabel();
        ulTextField = new javax.swing.JTextField();
        listBTN = new javax.swing.JButton();
        PriorityBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeJLabel.setForeground(java.awt.Color.blue);
        welcomeJLabel.setText("Gareth's Vacination Program");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameLabel.setText("Please enter your name");

        ulLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ulLabel.setForeground(new java.awt.Color(51, 51, 51));
        ulLabel.setText("Underlining Medical Conditions (YES/NO)");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        numVacBTN.setBackground(new java.awt.Color(153, 255, 255));
        numVacBTN.setText("No. Customers to be Vac");
        numVacBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numVacBTNActionPerformed(evt);
            }
        });

        addPatientBTN.setBackground(new java.awt.Color(204, 204, 0));
        addPatientBTN.setText("Add Patient");
        addPatientBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientBTNActionPerformed(evt);
            }
        });

        VacBTN.setBackground(new java.awt.Color(51, 255, 0));
        VacBTN.setText("Vacinate");
        VacBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacBTNActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        exitBTN.setBackground(new java.awt.Color(255, 102, 102));
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        ageLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(51, 51, 51));
        ageLabel.setText("Please enter your age");

        ulTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulTextFieldActionPerformed(evt);
            }
        });

        listBTN.setBackground(new java.awt.Color(255, 153, 255));
        listBTN.setText("List Patients to be Vac");
        listBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBTNActionPerformed(evt);
            }
        });

        PriorityBTN.setBackground(new java.awt.Color(51, 153, 255));
        PriorityBTN.setText("Priortise");
        PriorityBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PriorityBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addPatientBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PriorityBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(displayJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(numVacBTN)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(listBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(VacBTN))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ulLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(ageLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(ulTextField))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(welcomeJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(welcomeJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(numVacBTN)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ulLabel)
                            .addComponent(ulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addPatientBTN)
                            .addComponent(VacBTN)
                            .addComponent(PriorityBTN)
                            .addComponent(listBTN))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(displayJLabel)
                                .addGap(843, 843, 843))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(exitBTN)
                                .addContainerGap(835, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void numVacBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numVacBTNActionPerformed
        // TODO add your handling code here:
        textArea.append("There are " + myPQueue.size() + " patients already in the queue" + "\n");
    }//GEN-LAST:event_numVacBTNActionPerformed

    private void addPatientBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientBTNActionPerformed
        // TODO add your handling code here:
        String name, age, UM;

        name = nameTextField.getText();
        age = ageTextField.getText();
        UM = ulTextField.getText();

        n.add(name);
        a.add(age);
        u.add(UM.toLowerCase());

        textArea.append(nameTextField.getText() + " your details have been successfully added to the queue" + "\n");
        nameTextField.setText("");
        ageTextField.setText("");
        ulTextField.setText("");
    }//GEN-LAST:event_addPatientBTNActionPerformed

    private void VacBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacBTNActionPerformed
        // TODO add your handling code here:

        if (!myPQueue.isEmpty()) {
            PQElement pqelem = (PQElement) myPQueue.dequeue();
            Patient p1 = pqelem.getElement();

            textArea.append(" Next to be Vacinated is " + p1.getName());
            textArea.append("  Age: " + p1.getAge());
            textArea.append("  Priority: " + pqelem.getKey() + "\n");
        } else {
            textArea.append("There are no more to be vacinated" + "\n");
        }
    }//GEN-LAST:event_VacBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void ulTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ulTextFieldActionPerformed

    private void listBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBTNActionPerformed
        // TODO add your handling code here:
        textArea.append("To be Vacinated..." + "\n");
        textArea.append(myPQueue.printPQueue() + "\n");
    }//GEN-LAST:event_listBTNActionPerformed

    private void PriorityBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriorityBTNMouseClicked
        for (int i = 0; i < n.size(); i++) {
            Patient p = new Patient(); n.size(); 
            p.setName(n.get(i));
            p.setAge(a.get(i));
            p.setUl(u.get(i));

            String uli = u.get(i);

            String zx = a.get(i);
            int z = Integer.parseInt(zx);
            int pr = 0;

            if (z > 90) {
                pr = 10;
            }
            if (z > 80) {
                pr = 9;
            }
            if (z > 70) {
                pr = 8;
            }
            if (z >= 65 && z <= 69) {
                pr = 7;
            }

            if (z >= 55 && z <= 64) {
                pr = 5;
            }
            if (z >= 45 && z <= 54) {
                pr = 4;
            }
            if (z >= 30 && z <= 44) {
                pr = 3;
            }
            if (z >= 18 && z <= 29) {
                pr = 2;
            }

            if (z < 18) {
                pr = 1;
            }
            if (z >= 18 && z <= 64) {
                if (uli.equalsIgnoreCase("yes")) {
                    pr = 6;
                }
            }
            myPQueue.enqueue(pr, p);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_PriorityBTNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PriorityBTN;
    private javax.swing.JButton VacBTN;
    private javax.swing.JButton addPatientBTN;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JButton exitBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listBTN;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton numVacBTN;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel ulLabel;
    private javax.swing.JTextField ulTextField;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables

}
